### ISSUE TITLE
Socket hang up error sometimes

### ISSUE THREAD

**Issue by Barsonax** [fauna/faunadb-js#226]
Sometimes I get a socket hangup error from faunadb in my netlify function:
```
12:36:29 PM: 2020-02-13T11:36:29.083Z	00e2d3c8-39f5-48e4-b5c2-4341629d4ef9	ERROR	FetchError: request to https://db.fauna.com/ failed, reason: socket hang up
    at ClientRequest.<anonymous> (/var/task/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketOnEnd (_http_client.js:440:9)
    at TLSSocket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  message: 'request to https://db.fauna.com/ failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```
Tested with 2.9.2

**Comment by BrunoQuaresma** [comment]
Hi @Barsonax maybe this doc could be helpful https://docs.fauna.com/fauna/current/drivers/aws

**Comment by joshwcomeau** [comment]
Hi @BrunoQuaresma - I was getting the same issue, and the doc you shared fixed my problem 💯
Thanks so much!

**Comment by BrunoQuaresma** [comment]
Great @joshwcomeau ! @Barsonax closing this for now.
