### ISSUE TITLE
firebase-functions typescript cannot find name 'fetch'

### ISSUE THREAD

**Issue by alfiepoleon** [fauna/faunadb-js#262]
Adding faunadb to firebase functions typescript, and when I use import as so:
`import * as faunadb from 'faunadb';`
it throws an error when deploying
```bash
node_modules/faunadb/src/types/Client.d.ts:14:18 - error TS2304: Cannot find name 'fetch'.

14   fetch?: typeof fetch
```
I can't seem to use
``import faunadb, {q as query} from 'faunadb';``
this says throws `Module '".../node_modules/faunadb/index"' has no default export.`
Here is the npm log

 ```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/<user>/.nvm/versions/node/v12.16.2/bin/node',
1 verbose cli   '/home/<user>/.nvm/versions/node/v12.16.2/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   '/home/<user>/dev/work/<project>/<functions-directory>/functions',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle functions@~prebuild: functions@
6 info lifecycle functions@~build: functions@
7 verbose lifecycle functions@~build: unsafe-perm in lifecycle true
8 verbose lifecycle functions@~build: PATH: /home/<user>/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/<user>/dev/work/<project>/<functions-directory>/functions/node_modules/.bin:/home/<user>/.nvm/versions/node/v12.16.2/bin:/home/<user>/.local/bin:/home/<user>/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/<user>/dev/lib/flutter/bin:/home/<user>/dev/lib/flutter/bin
9 verbose lifecycle functions@~build: CWD: /home/<user>/dev/work/<project>/<functions-directory>/functions
10 silly lifecycle functions@~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle functions@~build: Returned: code: 2  signal: null
12 info lifecycle functions@~build: Failed to exec build script
13 verbose stack Error: functions@ build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/home/<user>/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/<user>/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid functions@
15 verbose cwd /home/<user>/dev/work/<project>/<functions-directory>
16 verbose Linux 5.4.33-3-MANJARO
17 verbose argv "/home/<user>/.nvm/versions/node/v12.16.2/bin/node" "/home/<user>/.nvm/versions/node/v12.16.2/bin/npm" "--prefix" "/home/<user>/dev/work/<project>/<functions-directory>/functions" "run" "build"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 2
22 error functions@ build: `tsc`
22 error Exit status 2
23 error Failed at the functions@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
 ```
It however works perfectly when I use `require`

**Comment by fauna-ryanharris** [comment]
@alfiepoleon Thanks for reporting this issue 👍 The issue here is that our JS Driver does not currently support ES module syntax (i.e. `import / export`) in Node environments. We are looking at adding this in the future, however, it will require a Node version of 13.2.0 or higher.

I am going to close this out as we will be revisiting it in the future. Thanks again!
