### ISSUE TITLE
breaking change on v2.14.0

### ISSUE THREAD

**Issue by vasco3** [fauna/faunadb-js#269]
When I upgrade from v2.13.0 to v2.14.0 the faunadb query returns with a non-JSON.
The same code in 2.13.0 works just fine.

Environment: Localhost
it is a "lambda function"

```js
export default async function org(req, res) {
  const adminClient = new faunadb.Client({
    secret: process.env.FAUNADB_SECRET,
    keepAlive: false,
  });

  const host = req?.headers['host'];
  const subdomain = getSubdomain({
    host,
    processSubdomain: process.env.SUBDOMAIN,
  });

  try {
    const matches = await adminClient.query(
      q.Paginate(
        q.Match(q.Index('orgsSecretByNameSpace'), q.Casefold(subdomain)),
      ),
    );
    const serverSecret = matches?.data[0];

    const childClient = new faunadb.Client({
      secret: serverSecret,
      keepAlive: false,
    });

    const settingsList = await childClient.query(
      q.Map(q.Paginate(q.Match(q.Index('settings'))), setting =>
        q.Select(['data'], q.Get(setting)),
      ),
    );

    const settings = keyBy(settingsList?.data || [], 'id');

    res.json({ settings, serverSecret, subdomain });
  } catch (error) {
    console.error(error);

    res.status(error.status || 500).json({
      error: error.message,
    });
  }
}```

**Comment by BrunoQuaresma** [comment]
@vasco3 could you please tell us what is the full error or what is the current result and what should be the expected one? Also, could you say please specifically where the error is happening? Thanks!

**Comment by vasco3** [comment]
getting this
```
Error: No valid exports main found for '/Users/jorgec/Downloads/code/sobras/node_modules/faunadb'
[1]     at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
[1]     at applyExports (internal/modules/cjs/loader.js:499:14)
[1]     at resolveExports (internal/modules/cjs/loader.js:548:12)
[1]     at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
[1]     at Module.require (internal/modules/cjs/loader.js:1028:19)
[1]     at require (internal/modules/cjs/helpers.js:72:18)
[1]     at Object.faunadb (/Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:197:18)
[1]     at __webpack_require__ (/Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:23:31)
[1]     at Module../src/pages/api/org.js (/Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:132:65)
[1]     at __webpack_require__ (/Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:23:31)
[1]     at Object.4 (/Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:185:18)
[1]     at __webpack_require__ (/Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:23:31)
[1]     at /Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:91:18
[1]     at Object.<anonymous> (/Users/jorgec/Downloads/code/sobras/.next/server/static/development/pages/api/org.js:94:10) {
[1]   code: 'MODULE_NOT_FOUND'
[1] }```

**Comment by roniemeque** [comment]
I'm getting the same error as @vasco3. My environment is also serverless, using Typescript and Vercel's cli. Please let me know if there is any additional info I can provide guys.

**Comment by BrunoQuaresma** [comment]
@vasco3 @roniemeque we are facing this issue on serverless environments in version 2.14.0. Sorry about that. Could you try please use the version 2.13.1 and see if it works for you?

**Comment by vasco3** [comment]
I'm also using it in vercel's serverless. 
2.13.1 works fine

**Comment by roniemeque** [comment]
Downgrading to 2.13.1 works 😁

**Comment by fauna-ryanharris** [comment]
@vasco3 @roniemeque We just released version `2.14.1`, which should resolve this issue. We rolled back the changes we made for ESM support on the client-side and will investigate adding this back.

Please let us know if `2.14.1` fixes your problem 👍

**Comment by vasco3** [comment]
@fauna-ryanharris thanks, that fixed it 👍

**Comment by fauna-ryanharris** [comment]
Thanks, @vasco3 🙌 Closing this as `2.14.1` fixed the issue.
