### ISSUE TITLE
v2.14.2 causes issues when `Match` term is not an array

### ISSUE THREAD

**Issue by bnoguchi** [fauna/faunadb-js#293]
Ever since I upgraded to `2.14.2`, I now get this exception:

```
TypeError: array.map is not a function
    at printArray (faunadb/src/Expr.js:119:8)
    at exprToString (faunadb/src/Expr.js:140:41)
    at map (faunadb/src/Expr.js:182:12)
    at Array.map (<anonymous>)
    at exprToString (faunadb/src/Expr.js:180:19)
    at map (faunadb/src/Expr.js:182:12)
    at Array.map (<anonymous>)
    at exprToString (faunadb/src/Expr.js:180:19)
    at faunadb/src/Expr.js:182:12
    at Array.map (<anonymous>)
```

This appears to be due to commit 5b6fa91cb53ffa82d2625314b625a947fa15d776 which does not handle a non-array single-term `Match` expression such as the following from the [Match docs](https://docs.fauna.com/fauna/current/api/fql/functions/match#examples):

```
client.query(
  q.Paginate(q.Match(q.Index('spells_by_element'), 'fire'))
)
.then((ret) => console.log(ret))
```

In my particular case, it is failing with the following expression:

```
q.Match(q.Index('spells_by_element'), q.Select("element", q.Var("input"))))
```

**Comment by fauna-ryanharris** [comment]
@bnoguchi I am closing this ticket as we have now addressed this issue in PR #298, which will go out as part of our next release. Thank you again for reporting the issue.
