### ISSUE TITLE
JSONparse error while bulk uploading large dataset

### ISSUE THREAD

**Issue by Alucard17** [fauna/faunadb-js#318]
I was trying to insert bulk insert large JSON dataset I got the following error. 
``` 
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseJSON (C:\Users\c3controls\Documents\projects\country-api\node_modules\faunadb\src\_json.js:16:15)
    at C:\Users\c3controls\Documents\projects\country-api\node_modules\faunadb\src\Client.js:186:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async syncCities (C:\Users\c3controls\Documents\projects\country-api\scripts\sync-data.js:75:5)
    at async syncALL (C:\Users\c3controls\Documents\projects\country-api\scripts\sync-data.js:107:9)
```

While debugging I found API gives the error in HTML format, `parseJSON` function in `_json.js`  tries to parse the following response.
```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

It should throw a correct exception for Entity Too large and batch Insert or bulk insert functionality would be handy.

**Comment by BrunoQuaresma** [comment]
Thanks for let us know @Alucard17. I opened a ticket(FE-730) internally to discuss this one.

**Comment by fireridlle** [comment]
@Alucard17 do you have any examples? I've tried to send 3mb json,seem to be ok now

**Comment by llaenowyd** [comment]
I hit this on a couple documents 4.2Mb and 6Mb.  Am I being unreasonable by expecting it to work?
