### ISSUE TITLE
Unable to check new driver version

### ISSUE THREAD

**Issue by louisholley** [fauna/faunadb-js#509]
i'm getting a lot of errors from a specific service on aws lambda. it's always these two errors together, and it seems to happen when the service is especially busy

```
Jun 28, 14:06:34 UTC
2021-06-28T14:06:34.080Z undefined ERROR Unable to check new driver version
Jun 28, 14:06:34 UTC
2021-06-28T14:06:34.083Z undefined ERROR
FetchError: request to https://registry.npmjs.org/faunadb failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/var/task/push.js:2389:16)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

i'm not sure if there's an issue with my setup (i'm instantiating the client within handlers, a la https://docs.fauna.com/fauna/current/drivers/known_issues.html), or if these errors are even pernicious but they seem to be coinciding with some service timeouts, so trying to get to the bottom of it!

**Comment by fireridlle** [comment]
This is just a warning. We will release the option to disable it soon
https://github.com/fauna/faunadb-js/pull/504
